### ISSUE TITLE
dns-3.0.0 doesn't build on GHC 7.8

### ISSUE THREAD

**Issue by YoEight** [kazu-yamamoto/dns#104]
Greetings,

I don't know if you still support GHC 7.8.4 (I happen to maintain a library that supports GHC 7.8.4 and has `dns` as a dependency)

My CI breaks like this:
```
Preprocessing library dns-3.0.0...
[ 1 of 14] Compiling Network.DNS.Types ( Network/DNS/Types.hs, dist/build/Network/DNS/Types.o )
[ 2 of 14] Compiling Network.DNS.Utils ( Network/DNS/Utils.hs, dist/build/Network/DNS/Utils.o )
[ 3 of 14] Compiling Network.DNS.Memo ( Network/DNS/Memo.hs, dist/build/Network/DNS/Memo.o )
[ 4 of 14] Compiling Network.DNS.Types.Internal ( Network/DNS/Types/Internal.hs, dist/build/Network/DNS/Types/Internal.o )
[ 5 of 14] Compiling Network.DNS.StateBinary ( Network/DNS/StateBinary.hs, dist/build/Network/DNS/StateBinary.o )
[ 6 of 14] Compiling Network.DNS.Encode ( Network/DNS/Encode.hs, dist/build/Network/DNS/Encode.o )

Network/DNS/Encode.hs:170:16: Not in scope: ‘pure’

Network/DNS/Encode.hs:170:21:
    Not in scope: ‘mempty’
    Perhaps you meant one of these:
      ‘BS.empty’ (imported from Data.ByteString.Char8),
      ‘LBS.empty’ (imported from Data.ByteString.Lazy.Char8)
```

Honestly, I don't know if some of my users still use this old GHC version. If you can't patch it, I'll happily drop 7.8 support :-)

Thanks for your time.

**Comment by kazu-yamamoto** [comment]
This has been fixed in `master`.

**Comment by YoEight** [comment]
@kazu-yamamoto Good to know. Is it possible to know when you will cut a new release?

**Comment by kazu-yamamoto** [comment]
Already released. :-)
